// packages/templates/template-ext-next/src/components/about.tsx
"use client"

import { ui } from "@kksh/api/ui/iframe"
import { useEffect } from "react"

export default function About() {
	useEffect(() => {
		ui.showBackButton("bottom-right")
	}, [])
	return (
		<div>
			<h1 className="text-xl font-bold">About Page</h1>
			<a href="./">Go To Home Page</a>
		</div>
	)
}

// packages/extensions/ext-sveltekit-exp/src/routes/about/+page.svelte
<script>
	import { base } from '$app/paths';
	import { Alert, Button, ThemeWrapper } from '@kksh/svelte';
</script>

<ThemeWrapper>
	<Alert.Root>
		<Alert.Title class="text-3xl font-bold">About Page</Alert.Title>
		<Alert.Description>
			<a href="{base}/">
				<Button>Home Page</Button>
			</a>
		</Alert.Description>
	</Alert.Root>
</ThemeWrapper>
